const canvas = document.querySelector('#canvas');
const canvasLines = canvas.getContext('2d');
canvasLines.beginPath();
canvasLines.lineWidth = 25;
canvasLines.strokeStyle = '#4FC6AE';
canvasLines.moveTo(125, 125);
canvasLines.lineTo(50, 225);
canvasLines.lineTo(125, 325);
canvasLines.stroke();
canvasLines.beginPath();
canvasLines.lineWidth = 25;
canvasLines.strokeStyle = 'black';
canvasLines.moveTo(200, 100);
canvasLines.lineTo(200, 350);
canvasLines.stroke();
canvasLines.beginPath();
canvasLines.lineWidth = 25;
canvasLines.strokeStyle = '#4FC6AE';
canvasLines.moveTo(350, 125);
canvasLines.lineTo(275, 225);
canvasLines.lineTo(350, 325);
canvasLines.stroke();
